mklink /J node_modules\superdup-auth-log superdup-auth-log
mklink /J node_modules\superdup-auth-core-providers superdup-auth-core-providers
mklink /J node_modules\superdup-auth-core-login superdup-auth-core-login
mklink /J node_modules\superdup-auth-core-tokens superdup-auth-core-tokens
mklink /J node_modules\superdup-auth-core-apis superdup-auth-core-apis
mklink /J node_modules\superdup-auth-core superdup-auth-core
mklink /J node_modules\superdup-auth-auth0js superdup-auth-auth0js
mklink /J node_modules\superdup-auth-oidc superdup-auth-oidc
mklink /J node_modules\superdup-auth-angular superdup-auth-angular
